FORMAT: 1A
HOST: http://localhost:3993

# scifgif

Humorous image microservice for isolated networks - xkcd and giphy full text search API

# Group xkcd
xkcd comic endpoints

## Random [/xkcd]
### Retrieve random xkcd comic [GET]

+ Response 200 (image/png)

## Number [/xkcd/number/{number}]
### Retrieve xkcd by number [GET]

+ Parameters
    + number: `1319` (number, required) - The xkcd comic ID

+ Response 200 (image/png)

## Search [/xkcd/search{?query}]
### Perform xkcd search [GET]

+ Parameters
  + query: `thumbs up` (string, required) - Search terms

+ Response 200 (image/png)

## Slash [/xkcd/slash{?text}]
### Post xkcd slash query [POST]

+ Parameters
  + text: `automation` (string, required) - Search terms

+ Request (application/json)

+ Response 200 (application/json; charset=UTF-8)

    + Attributes (object)
        + icon_url (string) - Slash command icon
        + response_type (string) - Mattermost response type
        + text (string) - Message text
        + username (string) - Mattermost username

    + Body

      {
          "icon_url": "http://localhost:3993/icon",
          "response_type": "in_channel",
          "text": "![gif](http://localhost:3993/images/default/xkcd.png)",
          "username": "xkcd"
      }

## Webhook [/xkcd/new_post]
### Post xkcd outgoing-webhook query [POST]

+ Attributes
  + channel_id: hawos4dqtby53pd64o4a4cmeoo (string)
  + channel_name: town-square (string)
  + team_domain: someteam (string)
  + team_id: kwoknj9nwpypzgzy78wkw516qe (string)
  + post_id: axdygg1957njfe5pu38saikdho (string)
  + text: some+text+here (string)
  + timestamp: 1445532266 (string)
  + token: zmigewsanbbsdf59xnmduzypjc (string)
  + trigger_word: some (string)
  + user_id: rnina9994bde8mua79zqcg5hmo (string)
  + user_name: somename (string)

+ Request (application/json)

+ Request (application/x-www-form-urlencoded)

  + Body

    channel_id=hawos4dqtby53pd64o4a4cmeoo&
    channel_name=town-square&
    team_domain=someteam&
    team_id=kwoknj9nwpypzgzy78wkw516qe&
    post_id=axdygg1957njfe5pu38saikdho&
    text=some+text+here&
    timestamp=1445532266&
    token=zmigewsanbbsdf59xnmduzypjc&
    trigger_word=some&
    user_id=rnina9994bde8mua79zqcg5hmo&
    user_name=somename

+ Response 200 (application/json; charset=UTF-8)

    + Attributes (object)
        + text (string) - Response text

    + Body

      {
        "text": "This is some response text."
      }

# Group giphy
giphy GIF endpoints

## Random [/giphy]
### Retrieve random giphy gif [GET]

+ Response 200 (image/gif)

## Search [/giphy/search{?query}]
### Retrieve giphy search [GET]

+ Parameters
  + query: `thumbs up` (string, required) - Search terms

+ Response 200 (image/gif)

## Slash [/giphy/slash{?text}]
### Post giphy slash query [POST]

+ Parameters
  + text: `thumbs up` (string, required) - Search terms

+ Response 200 (application/json; charset=UTF-8)

    + Attributes (object)
        + icon_url (string) - Slash command icon
        + response_type (string) - Mattermost response type
        + text (string) - Message text
        + username (string) - Mattermost username

    + Body

      {
          "icon_url": "http://localhost:3993/icon",
          "response_type": "in_channel",
          "text": "![gif](http://localhost:3993/images/default/xkcd.png)",
          "username": "scifgif"
      }

## Webhook [/giphy/new_post]
### Post giphy outgoing-webhook query [POST]

+ Attributes
  + channel_id: hawos4dqtby53pd64o4a4cmeoo (string)
  + channel_name: town-square (string)
  + team_domain: someteam (string)
  + team_id: kwoknj9nwpypzgzy78wkw516qe (string)
  + post_id: axdygg1957njfe5pu38saikdho (string)
  + text: some+text+here (string)
  + timestamp: 1445532266 (string)
  + token: zmigewsanbbsdf59xnmduzypjc (string)
  + trigger_word: some (string)
  + user_id: rnina9994bde8mua79zqcg5hmo (string)
  + user_name: somename (string)

+ Request (application/json)

+ Request (application/x-www-form-urlencoded)

  + Body

    channel_id=hawos4dqtby53pd64o4a4cmeoo&
    channel_name=town-square&
    team_domain=someteam&
    team_id=kwoknj9nwpypzgzy78wkw516qe&
    post_id=axdygg1957njfe5pu38saikdho&
    text=some+text+here&
    timestamp=1445532266&
    token=zmigewsanbbsdf59xnmduzypjc&
    trigger_word=some&
    user_id=rnina9994bde8mua79zqcg5hmo&
    user_name=somename

+ Response 200 (application/json; charset=UTF-8)

    + Attributes (object)
        + text (string) - Response text

    + Body

      {
        "text": "This is some response text."
      }

# Group image
image endpoints

## image [/image/{source}/{file}]
### Retrieve image [GET]

+ Parameters
    + source: `(xkcd|giphy)` (string, required) - The image source
    + file: `some.png` (string, required) - The image filename

## image [/image/{source}/{file}]
### Delete image [DELETE]
Allows users to delete possibly offensive images

+ Parameters
    + source: `(xkcd|giphy)` (string, required) - The image source
    + file: `some.png` (string, required) - The image filename

+ Response 200 (text/plain)

    + Body

      image successfully removed

# Group icon
icon endpoints

## xkcd [/icon/xkcd]
### Retrieve xkcd icon [GET]

+ Response 200 (image/jpeg)

## giphy [/icon/giphy]
### Retrieve giphy icon [GET]

+ Response 200 (image/png)
